const form=document.querySelector('#guestbook-form');
const messages=document.querySelector('.guestbook-messages');
const ownerButton=document.querySelector('#owner-mode');
const ownerState=document.querySelector('#owner-state');
const ownerKey='jason-portfolio-owner-token';
const apiUrl='https://jason-guestbook-api.jasono-oyg-1a8.workers.dev/api/messages';
const token=()=>sessionStorage.getItem(ownerKey);
const localKey='jason-portfolio-guestbook';
const local=()=>{try{return JSON.parse(localStorage.getItem(localKey))||[]}catch{return[]}};
function ownerUI(){const on=!!token();ownerState.textContent=on?'Reply mode enabled — posting as Jason':'Guest view — messages only';ownerButton.textContent=on?'Disable reply mode':'Jason? Enable reply mode'}
async function getEntries(){try{const r=await fetch(apiUrl);if(!r.ok)throw Error();return await r.json()}catch{return local()}}
async function render(){const list=await getEntries();messages.replaceChildren();list.slice(0,20).forEach((entry,index)=>{const a=document.createElement('article');a.className='guest-entry';a.innerHTML='<h3></h3><time></time><p></p><div class="replies"></div>';a.querySelector('h3').textContent=entry.name;a.querySelector('time').textContent=entry.created_at||entry.date;a.querySelector('p').textContent=entry.message;(entry.replies||[]).forEach(reply=>{const r=document.createElement('article');r.innerHTML='<h4>Jason</h4><time></time><p></p>';r.querySelector('time').textContent=reply.created_at||reply.date;r.querySelector('p').textContent=reply.message;a.querySelector('.replies').append(r)});if(token()){const b=document.createElement('button');b.className='reply-toggle';b.type='button';b.textContent='Reply as Jason ↗';b.onclick=()=>{let f=a.querySelector('.reply-form');if(f){f.remove();return}f=document.createElement('form');f.className='reply-form';f.innerHTML='<textarea maxlength="280" placeholder="Write your reply as Jason…" required></textarea><button>Post reply ↗</button>';f.onsubmit=async e=>{e.preventDefault();const message=f.querySelector('textarea').value.trim();if(!message)return;const r=await fetch(apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Token':token()},body:JSON.stringify({type:'reply',messageId:entry.id??index,message})});if(!r.ok){alert('Reply could not be posted.');return}render()};a.append(f)};const d=document.createElement('button');d.className='delete-toggle';d.type='button';d.textContent='Delete post';d.onclick=async()=>{if(!confirm('Delete this post and its replies?'))return;const r=await fetch(apiUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Token':token()},body:JSON.stringify({type:'delete',messageId:entry.id??index})});if(!r.ok){alert('Post could not be deleted.');return}render()};a.append(b,d)}messages.append(a)});ownerUI()}
ownerButton.onclick=()=>{if(token()){sessionStorage.removeItem(ownerKey);ownerUI();render();return}if(document.querySelector('.owner-login'))return;const f=document.createElement('form');f.className='owner-login';f.innerHTML='<input type="password" placeholder="Private owner token" required><button>Enable</button>';f.onsubmit=e=>{e.preventDefault();sessionStorage.setItem(ownerKey,f.querySelector('input').value.trim());f.remove();ownerUI();render()};ownerButton.insertAdjacentElement('afterend',f);f.querySelector('input').focus()};
form.onsubmit=async e=>{e.preventDefault();const d=new FormData(form),name=d.get('name').trim(),message=d.get('message').trim();if(!name||!message)return;const r=await fetch(apiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'message',name,message})});if(!r.ok){alert('Message could not be posted.');return}form.reset();render()};
ownerUI();render();
